replace ARK with ASA everywhere

diff --git a/tools/asamanager b/tools/asamanager
--- a/tools/asamanager
+++ b/tools/asamanager
@@ -1,7 +1,7 @@
 #!/bin/bash
 # shellcheck disable=SC2031,SC2155
 
-# ARK: survival evolved manager
+# ASA: survival evolved manager
 #
 # Original author:      LeXaT
 # Original Maintainer:  FezVrasta
@@ -108,10 +108,10 @@ doUpgradeToolsFromCommit(){
   rm -rf "$tmpdir"
 
   if [ "$result" = 0 ] || [ "$result" = 2 ]; then
-    echo "ARK Server Tools successfully upgraded"
+    echo "ASA Server Tools successfully upgraded"
     "${arkstScriptPath}" --version
   else
-    echo "ARK Server Tools upgrade failed"
+    echo "ASA Server Tools upgrade failed"
   fi
   exit $result
 }
@@ -132,13 +132,13 @@ doUpgradeToolsFromBranch(){
   REPLY=
 
   if [[ "$arkstLatestVersion" > "$arkstVersion" ]]; then
-    read -p "A new version was found! Do you want to upgrade ARK Server Tools to v${arkstLatestVersion}?" -n 1 -r
+    read -p "A new version was found! Do you want to upgrade ASA Server Tools to v${arkstLatestVersion}?" -n 1 -r
     echo
   elif [[ "$arkstLatestVersion" == "$arkstVersion" && "$arkstLatestCommit" != "$arkstCommit" ]]; then
     read -p "A hotfix is available for v${arkstLatestVersion}.  Do you wish to install it?" -n 1 -r
     echo
   else
-    echo "Your ARK server tools are already up to date"
+    echo "Your ASA server tools are already up to date"
   fi
 
   if [[ "$REPLY" =~ ^[Yy]$ ]]; then
@@ -171,7 +171,7 @@ doUpgradeToolsFromRelease(){
         doUpgradeToolsFromCommit "$commit"
       fi
     else
-      echo "Your ARK server tools are already up to date"
+      echo "Your ASA server tools are already up to date"
     fi
   else
     echo "Unable to get latest release"
@@ -187,7 +187,7 @@ doUninstallTools() {
       sudo=
     fi
 
-    read -p "Are you sure you want to uninstall the ARK Server Tools? [y/N]" -n 1 -r
+    read -p "Are you sure you want to uninstall the ASA Server Tools? [y/N]" -n 1 -r
 
     if [[ "$REPLY" =~ ^[Yy]$ ]]; then
       if [ -n "${install_datadir}" ] && [ -x "${install_datadir}/asamanager-uninstall.sh" ]; then
@@ -363,7 +363,7 @@ checkConfig() {
   if [ "$1" != "install" ] && [ -n "$instance" ]; then
     # arkserverexec
     if [ -n "$arkserverroot" ] && [ ! -f "$arkserverroot/$arkserverexec" ] ; then
-      echo -e "[" "$YELLOW" "WARN" "$NORMAL" "]" "\tYour ARK server exec could not be found." >&2
+      echo -e "[" "$YELLOW" "WARN" "$NORMAL" "]" "\tYour ASA server exec could not be found." >&2
     fi
 
     # SavedArks directory
@@ -371,12 +371,12 @@ checkConfig() {
       local savedarksdir="${arkserverroot}/${arkserverdir:-ShooterGame}/Saved/${ark_AltSaveDirectoryName:-SavedArks}"
       mkdir -p "${savedarksdir}"
       if [ ! -w "${savedarksdir}" ]; then
-        echo -e "[" "$RED" "ERROR" "$NORMAL" "]" "\tThe ARK SavedArks directory is not writable, and saveworld will fail" >&2
+        echo -e "[" "$RED" "ERROR" "$NORMAL" "]" "\tThe ASA SavedArks directory is not writable, and saveworld will fail" >&2
       fi
 
       mkdir -p "${arkserverroot}/${arkserverdir:-ShooterGame}/Content/Mods"
       if [ ! -w "${arkserverroot}/${arkserverdir:-ShooterGame}/Content/Mods" ]; then
-        echo -e "[" "$RED" "ERROR" "$NORMAL" "]" "\tThe ARK Mods directory is not writable, and installmod will fail" >&2
+        echo -e "[" "$RED" "ERROR" "$NORMAL" "]" "\tThe ASA Mods directory is not writable, and installmod will fail" >&2
       fi
     fi
 
@@ -1587,7 +1587,7 @@ doStartAll(){
 }
 
 #
-# stop the ARK server
+# stop the ASA server
 #
 doStop() {
   if [ "$1" != "update" ]; then
@@ -1675,7 +1675,7 @@ doStopAll(){
 }
 
 #
-# kills the ARK server
+# kills the ASA server
 #
 doKill() {
   logprint "Killing server"
@@ -1701,30 +1701,30 @@ runSteamCMDAppUpdate(){
 }
 
 #
-# install of ARK server
+# install of ASA server
 #
 doInstall() {
   # Check if arkserverroot already exists
   if [ ! -d "$arkserverroot" ]; then
     # If it does not exist, try create it
-    echo -e "Creating the ARK server root directory ($arkserverroot)"
+    echo -e "Creating the ASA server root directory ($arkserverroot)"
     mkdir -p "$arkserverroot"
     mkdir -p "${arkserverroot}/steamapps"
     if [ ! $? ] ; then
-      echo -e "[" "$RED" "ERROR" "$NORMAL" "]" "\tFailed to create the defined ARK server root directory ($arkserverroot)"
+      echo -e "[" "$RED" "ERROR" "$NORMAL" "]" "\tFailed to create the defined ASA server root directory ($arkserverroot)"
       exit 1
     fi
   fi
 
   cd "$steamcmdroot"
-  echo -n "Installing ARK server"
+  echo -n "Installing ASA server"
   # install the server
   doDownloadSteamCMD
   runSteamCMDAppUpdate "$arkserverroot" validate
   if [ $? -eq 5 ]; then
     echo "User ${steamlogin:-anonymous} login failed - please login to steamcmd manually"
   elif [ $? -eq 8 ]; then
-    echo "Insufficient disk space to install the ARK server"
+    echo "Insufficient disk space to install the ASA server"
   fi
   # the current version should be the last version. We set our version
   instver="$(getCurrentVersion)"
@@ -1820,13 +1820,13 @@ printWarnMessage(){
         if [ -n "$msgWarnUpdateMinutes" ]; then
           msg="${msgWarnUpdateMinutes//%d/$4}"
         else
-          msg="This ARK server will shutdown for an update in $4 minutes"
+          msg="This ASA server will shutdown for an update in $4 minutes"
         fi
       else
         if [ -n "$msgWarnUpdateSeconds" ]; then
           msg="${msgWarnUpdateSeconds//%d/$4}"
         else
-          msg="This ARK server will shutdown for an update in $4 seconds"
+          msg="This ASA server will shutdown for an update in $4 seconds"
         fi
       fi
     elif [ "$1" == "restart" ]; then
@@ -1834,13 +1834,13 @@ printWarnMessage(){
         if [ -n "$msgWarnRestartMinutes" ]; then
           msg="${msgWarnRestartMinutes//%d/$4}"
         else
-          msg="This ARK server will shutdown for a restart in $4 minutes"
+          msg="This ASA server will shutdown for a restart in $4 minutes"
         fi
       else
         if [ -n "$msgWarnRestartSeconds" ]; then
           msg="${msgWarnRestartSeconds//%d/$4}"
         else
-          msg="This ARK server will shutdown for a restart in $4 seconds"
+          msg="This ASA server will shutdown for a restart in $4 seconds"
         fi
       fi
     else
@@ -1848,13 +1848,13 @@ printWarnMessage(){
         if [ -n "$msgWarnShutdownMinutes" ]; then
           msg="${msgWarnShutdownMinutes//%d/$4}"
         else
-          msg="This ARK server will shutdown in $4 minutes"
+          msg="This ASA server will shutdown in $4 minutes"
         fi
       else
         if [ -n "$msgWarnShutdownSeconds" ]; then
           msg="${msgWarnShutdownSeconds//%d/$4}"
         else
-          msg="This ARK server will shutdown in $4 seconds"
+          msg="This ASA server will shutdown in $4 seconds"
         fi
       fi
     fi
@@ -2161,8 +2161,8 @@ doUpdate() {
       rm -f "$arkStagingDir/${arkserverdir}/Binaries/Linux/"*.txt
 
       if [ -z "$nodownload" ]; then
-        echo -n "Downloading ARK update"
-        logprint "Downloading ARK update" >/dev/null
+        echo -n "Downloading ASA update"
+        logprint "Downloading ASA update" >/dev/null
         doDownloadSteamCMD
         cd "$steamcmdroot"
         runSteamCMDAppUpdate "$arkStagingDir" ${appbeta:+-beta} $appbeta ${appbetapass:+-betapassword} $appbetapass $validate
@@ -2320,8 +2320,8 @@ doUpdate() {
           fi
         done
       else
-        echo -n "Performing ARK update"
-        logprint "Performing ARK update" >/dev/null
+        echo -n "Performing ASA update"
+        logprint "Performing ASA update" >/dev/null
         doDownloadSteamCMD
         cd "$steamcmdroot"
         runSteamCMDAppUpdate "$arkserverroot" ${appbeta:+-beta} $appbeta ${appbetapass:+-betapassword} $appbetapass $validate
@@ -2775,7 +2775,7 @@ isAnyModUpdateNeeded(){
 }
 
 #
-# Extracts a mod into the ARK Mods directory
+# Extracts a mod into the ASA Mods directory
 #
 doExtractMod(){
   local modid=$1
@@ -3110,8 +3110,8 @@ doBackup(){
 
   echo -e "${NORMAL} Saved arks directory is ${savedir}"
 
-  # ARK server uses Write-Unlink-Rename
-  echo -ne "${NORMAL} Copying ARK world file (${mapname}) "
+  # ASA server uses Write-Unlink-Rename
+  echo -ne "${NORMAL} Copying ASA world file (${mapname}) "
 
   local mapfile="${savedir}/${mapname}.ark"
 
@@ -3137,7 +3137,7 @@ doBackup(){
         logprint "Candidates:"
         for f in "${savedir}"/*.ark; do
           if [ "${f}" == "${f%_??.??.????_??.??.??.ark}" ]; then # Exclude auto-backups
-            logprint "  Saved ARK ${f}"
+            logprint "  Saved ASA ${f}"
           fi
         done
       fi
@@ -3148,7 +3148,7 @@ doBackup(){
 
   # Copy other world files
   if [ -n "$backupAllMaps" ] && [ "$backupAllMaps" != "false" ]; then
-    echo -e "${NORMAL} Copying other ARK world files"
+    echo -e "${NORMAL} Copying other ASA world files"
     for f in "${savedir}/"*.ark; do
       if [[ "${f}" != "${mapfile}" && "${f}" != "${savedir}/"*_??.??.????_??.??.??.ark ]]; then
         cp -p "${f}" "${backupdir}/${f##*/}"
@@ -3158,7 +3158,7 @@ doBackup(){
 
   # Copy map autobackups
   if [ -n "$includeAutoBackups" ] && [ "$includeAutoBackups" != "false" ]; then
-    echo -e "${NORMAL} Copying all ARK world autobackup files"
+    echo -e "${NORMAL} Copying all ASA world autobackup files"
     for f in "${savedir}/"*.ark; do
       if [[ "${f}" == "${savedir}/"*_??.??.????_??.??.??.ark ]]; then
         cp -p "${f}" "${backupdir}/${f##*/}"
@@ -3166,11 +3166,11 @@ doBackup(){
     done
   fi
 
-  # ARK server uses Lock-Truncate-Write-Unlock
+  # ASA server uses Lock-Truncate-Write-Unlock
   # Unfortunately we can't lock the file, as
-  # ARK server uses a non-blocking lock and will
+  # ASA server uses a non-blocking lock and will
   # fail to update the file if the lock fails.
-  echo -e "${NORMAL} Copying ARK profile files"
+  echo -e "${NORMAL} Copying ASA profile files"
   for f in "${savedir}/"*.arkprofile; do
     if [ -f "${f}" ]; then
       echo -ne "${NORMAL}   ${f##*/} "
@@ -3192,8 +3192,8 @@ doBackup(){
     fi
   done
 
-  # ARK server uses Lock-Truncate-Write-Unlock
-  echo -e "${NORMAL} Copying ARK tribe files "
+  # ASA server uses Lock-Truncate-Write-Unlock
+  echo -e "${NORMAL} Copying ASA tribe files "
   for f in "${savedir}/"*.arktribe; do
     if [ -f "${f}" ]; then
       echo -ne "${NORMAL}   ${f##*/} "
@@ -3215,8 +3215,8 @@ doBackup(){
     fi
   done
 
-  # ARK server uses Lock-Truncate-Write-Unlock
-  echo -e "${NORMAL} Copying ARK tribute tribe files "
+  # ASA server uses Lock-Truncate-Write-Unlock
+  echo -e "${NORMAL} Copying ASA tribute tribe files "
   for f in "${savedir}/"*.arktributetribe; do
     if [ -f "${f}" ]; then
       echo -ne "${NORMAL}   ${f##*/} "
@@ -3248,7 +3248,7 @@ doBackup(){
     cp -av "${clusterdir}" "${backupdir}/Cluster"
   fi
 
-  # ARK server uses Lock-Truncate-Write-Unlock
+  # ASA server uses Lock-Truncate-Write-Unlock
   echo -ne "${NORMAL} Copying GameUserSettings.ini "
   cp -p "${savedcfgdir}/GameUserSettings.ini" "${backupdir}/GameUserSettings.ini"
   if [ ! -s "${backupdir}/GameUserSettings.ini" ]; then
@@ -3789,13 +3789,13 @@ showUsage() {
 
 	Commands that take no instances:
 	Command               Description
-	upgrade-tools         Check for a new ARK Server Tools version and upgrades it if needed
-	uninstall-tools       Uninstall the ARK Server Tools
+	upgrade-tools         Check for a new ASA Server Tools version and upgrades it if needed
+	uninstall-tools       Uninstall the ASA Server Tools
 	useconfig <name>      Sets the default instance for the commands that follow
 	remove-mods <modid>   Remove one or more mods from the steamcmd workshop directory
 	list-instances        Lists all available instances
 	--help                Show this help
-	--version             Show the version info of ARK Server Tools
+	--version             Show the version info of ASA Server Tools
 
 	Commands that take one or more instances:
 	Command               Description
@@ -3804,9 +3804,9 @@ showUsage() {
 	broadcast <msg>       Sends a message to all users connected to server
 	saveworld             Saves the game world to disk
 	rconcmd <cmd>         Execute RCON command on server
-	checkupdate           Check for a new ARK server version
+	checkupdate           Check for a new ASA server version
 	checkmodupdate        Checks for any mods needing updates
-	install               Install the ARK server files from steamcmd
+	install               Install the ASA server files from steamcmd
 	installmod <modid>    Installs a mod from the Steam workshop
 	uninstallmod <modid>  Removes the mod from the Mods directory
 	reinstallmod <modid>  Removes and re-installs a mod in the Mods directory
@@ -3822,10 +3822,10 @@ showUsage() {
 	stop                  Stops the server
   kill                  kills the server
 	cancelshutdown        Aborts a running stop --warn or update --warn
-	status                Returns the status of the current ARK server instance
+	status                Returns the status of the current ASA server instance
 	printconfig           Displays which settings are sourced from which config file
 	getpid                Gets the running server PID
-	update                Check for a new ARK server version, if needed, stops the server, updates it, and starts it again
+	update                Check for a new ASA server version, if needed, stops the server, updates it, and starts it again
 
 	Commands which invoke steamcmd take the following options:
 	   --verbose          Show steamcmd output
@@ -3837,7 +3837,7 @@ showUsage() {
 	   --safe             Wait for server to perform world save and update (deprecated, use --saveworld)
 	   --warn             Warn players before updating server
 	   --ifempty          Apply the update only if no players are connected
-	   --validate         Validates all ARK server files
+	   --validate         Validates all ASA server files
 	   --saveworld        Saves world before update
 	   --update-mods      Updates installed and requested mods
 	   --backup           Takes a backup of the save files before updating
@@ -3860,7 +3860,7 @@ showUsage() {
 	   --noautoupdate     Disable any automatic update that may be enabled in the config
 	   --alwaysrestart    Always restart server on crash, even if it did not finish starting
 	   --no-background    Run the server without going into the background
-	   --arkopt,opt=val   Add an ARK option:
+	   --arkopt,opt=val   Add an ASA option:
 	      -opt=val        Equivalent to adding arkopt_opt=val to config for this run
 	      -opt            Equivalent to adding arkflag_opt=true to config for this run
 	      opt=val         Equivalent to adding ark_opt=val to config for this run
